"""Research report generation helpers."""

from .audit_review import (
    StrategyPromotionAuditReviewArtifact,
    StrategyPromotionAuditReviewContext,
    generate_strategy_promotion_audit_review,
)
from .backlog import (
    ReviewBacklogArtifact,
    ReviewBacklogRecord,
    ReviewBacklogRecordType,
    create_review_backlog,
)
from .citations import (
    BibtexArtifact,
    CitationGenerationError,
    CitationStatus,
    CitationValidation,
    generate_bibtex,
    validate_citations,
)
from .drafts import (
    PaperDraftVersion,
    PaperDraftVersioningError,
    store_paper_draft_version,
)
from .evidence_gate import (
    EvidenceGateCheck,
    EvidenceGateCheckStatus,
    EvidenceGateReport,
    EvidenceGateVerdict,
    EvidenceLifecycleStage,
    run_evidence_gate,
)
from .evolution import (
    StrategyEvolutionReportArtifact,
    StrategyEvolutionReportContext,
    generate_strategy_evolution_report,
)
from .figures import FigureArtifact, FigureGenerationError, generate_metric_bar_figure
from .generator import ReportContext, generate_markdown_report
from .latex import (
    LatexCompilationError,
    LatexDraftArtifact,
    LatexDraftContext,
    LatexGenerationError,
    generate_latex_skeleton,
)
from .latex_templates import (
    LatexTemplateCompatibilityReport,
    LatexTemplateCompatibilityResult,
    LatexTemplateCompatibilityStatus,
    LatexTemplateSourceFetchStatus,
    LatexTemplateSourceKind,
    LatexTemplateSourceMetadata,
    LatexTemplateSpec,
    external_latex_templates,
    generic_latex_templates,
    render_latex_template_smoke,
    run_latex_template_compatibility,
)
from .lint import (
    ReportLintError,
    ReportLintIssue,
    assert_metric_consistency,
    assert_report_readable,
    lint_markdown_report,
    lint_metric_consistency,
)
from .paper_build import (
    LatexPaperBuildArtifact,
    LatexPaperBuildStatus,
    build_latex_paper_from_markdown,
)
from .publication_audit import (
    PublicationAuditCheck,
    PublicationAuditCheckStatus,
    PublicationAuditReport,
    PublicationAuditVerdict,
    PublicationQualityTarget,
    audit_publication_quality,
)
from .reproducibility import (
    ExcludedReproducibilityArtifact,
    ReproducibilityArtifactInput,
    ReproducibilityArtifactRole,
    ReproducibilityPackage,
    ReproducibilityPackageArtifact,
    ReproducibilityPackageError,
    ReproducibilityPackageIssue,
    ReproducibilityPackageValidation,
    create_reproducibility_package,
    validate_reproducibility_package,
)
from .review import (
    PaperReviewContext,
    PaperReviewReport,
    ReviewCriteria,
    ReviewCriteriaError,
    ReviewDimension,
    ReviewDimensionScore,
    ReviewFinding,
    load_review_criteria,
    simulate_paper_review,
)
from .tables import (
    MetricsTableArtifact,
    MetricsTableInput,
    TableGenerationError,
    generate_ablation_table,
    generate_method_comparison_table,
)

__all__ = [
    "BibtexArtifact",
    "CitationGenerationError",
    "CitationStatus",
    "CitationValidation",
    "EvidenceGateCheck",
    "EvidenceGateCheckStatus",
    "EvidenceGateReport",
    "EvidenceGateVerdict",
    "EvidenceLifecycleStage",
    "FigureArtifact",
    "FigureGenerationError",
    "LatexCompilationError",
    "LatexDraftArtifact",
    "LatexDraftContext",
    "LatexGenerationError",
    "LatexTemplateCompatibilityReport",
    "LatexTemplateCompatibilityResult",
    "LatexTemplateCompatibilityStatus",
    "LatexTemplateSourceFetchStatus",
    "LatexTemplateSourceKind",
    "LatexTemplateSourceMetadata",
    "LatexTemplateSpec",
    "LatexPaperBuildArtifact",
    "LatexPaperBuildStatus",
    "MetricsTableArtifact",
    "MetricsTableInput",
    "PaperDraftVersion",
    "PaperDraftVersioningError",
    "PublicationAuditCheck",
    "PublicationAuditCheckStatus",
    "PublicationAuditReport",
    "PublicationAuditVerdict",
    "PublicationQualityTarget",
    "ReviewBacklogArtifact",
    "ReviewBacklogRecord",
    "ReviewBacklogRecordType",
    "ReviewCriteria",
    "ReviewCriteriaError",
    "PaperReviewContext",
    "PaperReviewReport",
    "ReportContext",
    "ReportLintError",
    "ReportLintIssue",
    "ExcludedReproducibilityArtifact",
    "ReproducibilityArtifactInput",
    "ReproducibilityArtifactRole",
    "ReproducibilityPackage",
    "ReproducibilityPackageArtifact",
    "ReproducibilityPackageError",
    "ReproducibilityPackageIssue",
    "ReproducibilityPackageValidation",
    "ReviewDimension",
    "ReviewDimensionScore",
    "ReviewFinding",
    "StrategyEvolutionReportArtifact",
    "StrategyEvolutionReportContext",
    "StrategyPromotionAuditReviewArtifact",
    "StrategyPromotionAuditReviewContext",
    "TableGenerationError",
    "assert_metric_consistency",
    "assert_report_readable",
    "audit_publication_quality",
    "build_latex_paper_from_markdown",
    "create_review_backlog",
    "create_reproducibility_package",
    "generate_bibtex",
    "generate_ablation_table",
    "generate_strategy_promotion_audit_review",
    "generate_strategy_evolution_report",
    "generate_metric_bar_figure",
    "generate_method_comparison_table",
    "generate_latex_skeleton",
    "external_latex_templates",
    "generic_latex_templates",
    "lint_metric_consistency",
    "load_review_criteria",
    "generate_markdown_report",
    "lint_markdown_report",
    "render_latex_template_smoke",
    "run_latex_template_compatibility",
    "run_evidence_gate",
    "simulate_paper_review",
    "store_paper_draft_version",
    "validate_reproducibility_package",
    "validate_citations",
]
