"""Research report generation helpers."""

from .backlog import (
    ReviewBacklogArtifact,
    ReviewBacklogRecord,
    ReviewBacklogRecordType,
    create_review_backlog,
)
from .citations import (
    BibtexArtifact,
    CitationGenerationError,
    CitationStatus,
    CitationValidation,
    generate_bibtex,
    validate_citations,
)
from .drafts import (
    PaperDraftVersion,
    PaperDraftVersioningError,
    store_paper_draft_version,
)
from .evolution import (
    StrategyEvolutionReportArtifact,
    StrategyEvolutionReportContext,
    generate_strategy_evolution_report,
)
from .figures import FigureArtifact, FigureGenerationError, generate_metric_bar_figure
from .generator import ReportContext, generate_markdown_report
from .latex import (
    LatexCompilationError,
    LatexDraftArtifact,
    LatexDraftContext,
    LatexGenerationError,
    generate_latex_skeleton,
)
from .lint import (
    ReportLintError,
    ReportLintIssue,
    assert_metric_consistency,
    assert_report_readable,
    lint_markdown_report,
    lint_metric_consistency,
)
from .reproducibility import (
    ExcludedReproducibilityArtifact,
    ReproducibilityArtifactInput,
    ReproducibilityArtifactRole,
    ReproducibilityPackage,
    ReproducibilityPackageArtifact,
    ReproducibilityPackageError,
    ReproducibilityPackageIssue,
    ReproducibilityPackageValidation,
    create_reproducibility_package,
    validate_reproducibility_package,
)
from .review import (
    PaperReviewContext,
    PaperReviewReport,
    ReviewCriteria,
    ReviewCriteriaError,
    ReviewDimension,
    ReviewDimensionScore,
    ReviewFinding,
    load_review_criteria,
    simulate_paper_review,
)
from .tables import (
    MetricsTableArtifact,
    MetricsTableInput,
    TableGenerationError,
    generate_ablation_table,
    generate_method_comparison_table,
)

__all__ = [
    "BibtexArtifact",
    "CitationGenerationError",
    "CitationStatus",
    "CitationValidation",
    "FigureArtifact",
    "FigureGenerationError",
    "LatexCompilationError",
    "LatexDraftArtifact",
    "LatexDraftContext",
    "LatexGenerationError",
    "MetricsTableArtifact",
    "MetricsTableInput",
    "PaperDraftVersion",
    "PaperDraftVersioningError",
    "ReviewBacklogArtifact",
    "ReviewBacklogRecord",
    "ReviewBacklogRecordType",
    "ReviewCriteria",
    "ReviewCriteriaError",
    "PaperReviewContext",
    "PaperReviewReport",
    "ReportContext",
    "ReportLintError",
    "ReportLintIssue",
    "ExcludedReproducibilityArtifact",
    "ReproducibilityArtifactInput",
    "ReproducibilityArtifactRole",
    "ReproducibilityPackage",
    "ReproducibilityPackageArtifact",
    "ReproducibilityPackageError",
    "ReproducibilityPackageIssue",
    "ReproducibilityPackageValidation",
    "ReviewDimension",
    "ReviewDimensionScore",
    "ReviewFinding",
    "StrategyEvolutionReportArtifact",
    "StrategyEvolutionReportContext",
    "TableGenerationError",
    "assert_metric_consistency",
    "assert_report_readable",
    "create_review_backlog",
    "create_reproducibility_package",
    "generate_bibtex",
    "generate_ablation_table",
    "generate_strategy_evolution_report",
    "generate_metric_bar_figure",
    "generate_method_comparison_table",
    "generate_latex_skeleton",
    "lint_metric_consistency",
    "load_review_criteria",
    "generate_markdown_report",
    "lint_markdown_report",
    "simulate_paper_review",
    "store_paper_draft_version",
    "validate_reproducibility_package",
    "validate_citations",
]
