"""Agent runtime primitives."""

from typing import TYPE_CHECKING, Any

from .base import (
    AgentCapabilityError,
    AgentLifecycleState,
    AgentResult,
    AgentResultStatus,
    AgentTask,
    BaseAgent,
)
from .mcp_evidence import (
    MCP_INVOCATION_EVIDENCE_KIND,
    MCP_INVOCATION_EVIDENCE_POLICY,
    AgentMcpInvocationEvidence,
    McpInvocationEvidenceValidation,
    McpInvocationStatus,
    append_mcp_invocation_evidence,
    build_mcp_invocation_evidence,
    load_mcp_invocation_evidence,
    validate_mcp_invocation_evidence,
    write_mcp_invocation_validation_report,
)
from .messages import AgentMessage, MessageRiskLevel
from .profiles import (
    DEFAULT_AGENT_PROFILE_SET_REQUIRED_STAGES,
    DEFAULT_SKILL_MATERIALIZATION_MAX_CHARS,
    PROFILE_SET_EVIDENCE_POLICY,
    AgentMcpRuntimeContract,
    AgentMcpServerBinding,
    AgentProfile,
    AgentProfileBundle,
    AgentProfileBundleMcpServer,
    AgentProfileBundleSkill,
    AgentProfileReadinessCheck,
    AgentProfileReadinessReport,
    AgentProfileReadinessStatus,
    AgentProfileSetBundle,
    AgentProfileSetValidation,
    AgentProfileStageCoverage,
    AgentSkillBinding,
    AgentSkillMaterializationStatus,
    AgentSkillMaterializedContext,
    AgentThinkingMode,
    McpApprovalPolicy,
    SkillImportPolicy,
    SkillSourceType,
    build_agent_mcp_runtime_contracts,
    build_agent_profile_from_bundle,
    build_agent_profiles_from_set_bundle,
    build_agent_stage_assignment_manifest,
    build_agent_stage_context_packet,
    evaluate_agent_profile_readiness,
    evaluate_agent_profile_set,
    load_agent_profile,
    load_agent_profile_bundle,
    load_agent_profile_set_bundle,
    materialize_agent_skill_contexts,
    normalize_profile_stage,
    parse_mcp_approval_policy_specs,
    parse_mcp_env_key_specs,
    parse_mcp_spec,
    parse_server_tool_specs,
    parse_skill_policy_specs,
    parse_skill_spec,
    profile_contexts_by_stage,
    profile_contexts_for_stage,
    render_agent_profile_markdown,
    render_agent_stage_runtime_prompt,
    write_agent_profile,
    write_agent_profile_note,
)
from .registry import AgentRegistry, AgentRegistryError

if TYPE_CHECKING:
    from .workflow import (
        ResearchWorkflow,
        ResearchWorkflowStage,
        ResearchWorkflowState,
        WorkflowCheckpointStore,
    )

_WORKFLOW_EXPORTS = {
    "ResearchWorkflow",
    "ResearchWorkflowStage",
    "ResearchWorkflowState",
    "WorkflowCheckpointStore",
}


def __getattr__(name: str) -> Any:
    if name in _WORKFLOW_EXPORTS:
        from . import workflow

        return getattr(workflow, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

__all__ = [
    "AgentCapabilityError",
    "AgentLifecycleState",
    "AgentMessage",
    "AgentMcpInvocationEvidence",
    "AgentMcpServerBinding",
    "AgentMcpRuntimeContract",
    "AgentProfile",
    "AgentProfileBundle",
    "AgentProfileBundleMcpServer",
    "AgentProfileBundleSkill",
    "AgentProfileReadinessCheck",
    "AgentProfileReadinessReport",
    "AgentProfileReadinessStatus",
    "AgentProfileSetBundle",
    "AgentProfileSetValidation",
    "AgentProfileStageCoverage",
    "AgentRegistry",
    "AgentRegistryError",
    "AgentResult",
    "AgentResultStatus",
    "AgentSkillBinding",
    "AgentSkillMaterializationStatus",
    "AgentSkillMaterializedContext",
    "AgentTask",
    "AgentThinkingMode",
    "BaseAgent",
    "DEFAULT_AGENT_PROFILE_SET_REQUIRED_STAGES",
    "DEFAULT_SKILL_MATERIALIZATION_MAX_CHARS",
    "MCP_INVOCATION_EVIDENCE_KIND",
    "MCP_INVOCATION_EVIDENCE_POLICY",
    "PROFILE_SET_EVIDENCE_POLICY",
    "McpApprovalPolicy",
    "McpInvocationEvidenceValidation",
    "McpInvocationStatus",
    "MessageRiskLevel",
    "ResearchWorkflow",
    "ResearchWorkflowStage",
    "ResearchWorkflowState",
    "SkillImportPolicy",
    "SkillSourceType",
    "WorkflowCheckpointStore",
    "append_mcp_invocation_evidence",
    "build_agent_mcp_runtime_contracts",
    "build_agent_profile_from_bundle",
    "build_agent_profiles_from_set_bundle",
    "build_agent_stage_assignment_manifest",
    "build_agent_stage_context_packet",
    "build_mcp_invocation_evidence",
    "evaluate_agent_profile_readiness",
    "evaluate_agent_profile_set",
    "load_agent_profile",
    "load_agent_profile_bundle",
    "load_agent_profile_set_bundle",
    "load_mcp_invocation_evidence",
    "materialize_agent_skill_contexts",
    "normalize_profile_stage",
    "parse_mcp_approval_policy_specs",
    "parse_mcp_env_key_specs",
    "parse_mcp_spec",
    "parse_server_tool_specs",
    "parse_skill_policy_specs",
    "parse_skill_spec",
    "profile_contexts_by_stage",
    "profile_contexts_for_stage",
    "render_agent_profile_markdown",
    "render_agent_stage_runtime_prompt",
    "validate_mcp_invocation_evidence",
    "write_agent_profile",
    "write_agent_profile_note",
    "write_mcp_invocation_validation_report",
]
