"""Persistent, evidence-first autonomous research campaigns."""

from .models import (
    CampaignManifest,
    CampaignOutcome,
    CampaignPolicy,
    CampaignResult,
    CampaignRoundDesign,
    CampaignSpec,
    CampaignStage,
    CampaignTrack,
    ContributionGateResult,
    DevelopmentResult,
    FailureDiagnosis,
    FailureKind,
    FreezeInputs,
    FrozenRoundProtocol,
    HypothesisProposal,
    HypothesisScreening,
    Preregistration,
    PreregistrationInputs,
    RoundDecision,
    RoundDecisionKind,
    RoundDevelopmentContext,
    RoundManifest,
    RoundObservation,
    RoundOutcome,
    UnseenEvaluation,
)
from .service import (
    AutonomousResearchCampaign,
    CampaignIntegrityError,
    CampaignResearchAdapter,
    load_campaign_manifest,
    load_round_manifest,
)

__all__ = [
    "AutonomousResearchCampaign",
    "CampaignIntegrityError",
    "CampaignManifest",
    "CampaignOutcome",
    "CampaignPolicy",
    "CampaignResearchAdapter",
    "CampaignResult",
    "CampaignRoundDesign",
    "CampaignSpec",
    "CampaignStage",
    "CampaignTrack",
    "ContributionGateResult",
    "DevelopmentResult",
    "FailureDiagnosis",
    "FailureKind",
    "FreezeInputs",
    "FrozenRoundProtocol",
    "HypothesisProposal",
    "HypothesisScreening",
    "Preregistration",
    "PreregistrationInputs",
    "RoundDecision",
    "RoundDecisionKind",
    "RoundDevelopmentContext",
    "RoundManifest",
    "RoundObservation",
    "RoundOutcome",
    "UnseenEvaluation",
    "load_campaign_manifest",
    "load_round_manifest",
]

