"""Minimal Typer CLI for the AI-Researcher Phase 0 scaffold."""

import json
import sys
from collections.abc import Iterable
from importlib import import_module
from pathlib import Path
from typing import Annotated

import typer
from dotenv import load_dotenv

from autoresearch import __version__
from autoresearch.config import (
    ConfigFormat,
    ConfigParser,
    DeploymentConfig,
    MessagingChannelConfig,
    ModelProviderConfig,
    SystemConfig,
)
from autoresearch.experiments import run_scientistbench_demo
from autoresearch.literature import LiteratureRefreshConfig, run_daily_literature_refresh
from autoresearch.llm import LLMClientError, run_llm_smoke_test
from autoresearch.reports import validate_reproducibility_package
from autoresearch.research import (
    SimilarityCheckConfig,
    link_similarity_report_to_project,
    run_project_similarity_check,
)
from autoresearch.schemas import ResearchCandidate, ValidationStatus

app = typer.Typer(
    help="AI-Researcher command line interface.",
    no_args_is_help=True,
)
slash_app = typer.Typer(help="Manage project slash command templates.")
app.add_typer(slash_app, name="slash-commands")

DEFAULT_SLASH_COMMANDS = {
    "research/refresh-literature.toml": (
        "Fetch real literature sources and write a guarded Obsidian summary.",
        "Run `autoresearch literature-refresh --live --vault autoresearch-vault --cache .cache/literature` "
        "and summarize source-backed new papers only. Do not infer paper results, code "
        "availability, or benchmark scores unless the fetched source explicitly provides them.",
    ),
    "research/similarity-check.toml": (
        "Cross-check a candidate against adjacent online work before project approval.",
        "Run `autoresearch similarity-check --candidate-file <candidate.json> --live` for {{args}}. "
        "Use source URLs and DOI evidence only; unsupported outcomes must remain pending verification.",
    ),
    "research/run-demo.toml": (
        "Run a local ScientistBench-Lite demo and inspect evidence outputs.",
        "Run `autoresearch run-demo --demo {{args}}` or default to tabular_baseline. "
        "Review the validation report, evidence map, and Markdown report before making claims.",
    ),
    "research/status.toml": (
        "Check local installation and release-readiness gates.",
        "Run `autoresearch doctor`, then inspect `Problem.md`, `Agent.md`, and the latest git status. "
        "Report blockers before proposing more automation.",
    ),
}

ENV_EXAMPLE_TEXT = """# Local deployment secrets for AI-Researcher.
# Generated by `autoresearch deploy-setup` when the template is missing.
# Copy this file to .env or rerun the setup command to write real local values.
# Never commit real API keys, webhook URLs, app secrets, or tokens.

AUTORESEARCH_LLM_PROVIDER=openai-compatible
AUTORESEARCH_LLM_BASE_URL=
AUTORESEARCH_LLM_MODEL_NAME=
AUTORESEARCH_LLM_API_KEY=

# Optional Semantic Scholar Graph API key for higher rate limits.
SEMANTIC_SCHOLAR_API_KEY=

# Optional WeChat channel.
AUTORESEARCH_WECHAT_WEBHOOK_URL=
AUTORESEARCH_WECHAT_APP_ID=
AUTORESEARCH_WECHAT_APP_SECRET=

# Optional Feishu channel.
AUTORESEARCH_FEISHU_WEBHOOK_URL=
AUTORESEARCH_FEISHU_APP_ID=
AUTORESEARCH_FEISHU_APP_SECRET=
"""


@app.command()
def version() -> None:
    """Print the installed AI-Researcher version."""

    typer.echo(__version__)


@app.command()
def doctor() -> None:
    """Check local scaffold health without contacting external services."""

    config = SystemConfig()
    checks = [
        (
            "python >= 3.10",
            sys.version_info >= (3, 10),
            sys.version.split()[0],
        ),
        (
            "import autoresearch",
            _can_import("autoresearch"),
            "package import",
        ),
        (
            "import autoresearch.config",
            _can_import("autoresearch.config"),
            "config import",
        ),
        (
            "config parser",
            _parser_available(),
            "JSON/YAML/TOML parser",
        ),
        (
            "project root",
            config.project_root.exists(),
            str(config.project_root),
        ),
        (
            "knowledge vault",
            config.knowledge_base.vault_path.exists(),
            str(config.knowledge_base.vault_path),
        ),
    ]

    failed = False
    for name, ok, detail in checks:
        label = "OK" if ok else "FAIL"
        typer.echo(f"[{label}] {name}: {detail}")
        failed = failed or not ok

    if failed:
        raise typer.Exit(code=1)


@app.command("init-demo")
def init_demo(
    path: Path = typer.Option(
        Path("examples/demo"),
        "--path",
        "-p",
        help="Directory where the local demo scaffold should be created.",
    ),
) -> None:
    """Create a local demo scaffold without running a research workflow."""

    path.mkdir(parents=True, exist_ok=True)
    config = SystemConfig(project_root=path)
    parser = ConfigParser()

    readme_path = path / "README.md"
    config_path = path / "config.yaml"

    if not readme_path.exists():
        readme_path.write_text(
            "# AI-Researcher Demo\n\n"
            "This scaffold is created by `autoresearch init-demo`.\n"
            "It does not run the research workflow yet.\n",
            encoding="utf-8",
        )
    if not config_path.exists():
        parser.write_file(config, config_path, ConfigFormat.YAML)

    typer.echo(f"Demo scaffold ready at {path}")


@app.command("deploy-setup")
def deploy_setup(
    config_path: Annotated[
        Path,
        typer.Option(
            "--config",
            "-c",
            help="Configuration file to create or update.",
        ),
    ] = Path("config.yaml"),
    env_path: Annotated[
        Path,
        typer.Option(
            "--env-path",
            help="Local .env file for secrets and channel credentials.",
        ),
    ] = Path(".env"),
    provider: Annotated[
        str | None,
        typer.Option("--provider", help="LLM provider label, for example openai-compatible."),
    ] = None,
    base_url: Annotated[
        str | None,
        typer.Option("--base-url", help="OpenAI-compatible API base URL."),
    ] = None,
    model_name: Annotated[
        str | None,
        typer.Option("--model-name", help="Model name to use for first deployment."),
    ] = None,
    api_key: Annotated[
        str | None,
        typer.Option("--api-key", help="LLM API key. Stored only in .env."),
    ] = None,
    wechat: Annotated[
        bool | None,
        typer.Option("--wechat/--no-wechat", help="Configure the WeChat channel."),
    ] = None,
    wechat_webhook_url: Annotated[
        str | None,
        typer.Option("--wechat-webhook-url", help="WeChat webhook URL stored in .env."),
    ] = None,
    wechat_app_id: Annotated[
        str | None,
        typer.Option("--wechat-app-id", help="WeChat app ID stored in .env."),
    ] = None,
    wechat_app_secret: Annotated[
        str | None,
        typer.Option("--wechat-app-secret", help="WeChat app secret stored in .env."),
    ] = None,
    feishu: Annotated[
        bool | None,
        typer.Option("--feishu/--no-feishu", help="Configure the Feishu channel."),
    ] = None,
    feishu_webhook_url: Annotated[
        str | None,
        typer.Option("--feishu-webhook-url", help="Feishu webhook URL stored in .env."),
    ] = None,
    feishu_app_id: Annotated[
        str | None,
        typer.Option("--feishu-app-id", help="Feishu app ID stored in .env."),
    ] = None,
    feishu_app_secret: Annotated[
        str | None,
        typer.Option("--feishu-app-secret", help="Feishu app secret stored in .env."),
    ] = None,
    non_interactive: Annotated[
        bool,
        typer.Option("--non-interactive", help="Fail on missing required inputs instead of prompting."),
    ] = False,
) -> None:
    """Run first-deploy setup for model API credentials and chat channels."""

    provider_value = _required_value(
        provider,
        prompt="LLM provider label",
        default="openai-compatible",
        non_interactive=non_interactive,
    )
    base_url_value = _required_value(
        base_url,
        prompt="LLM API base URL",
        default="https://api.openai.com/v1",
        non_interactive=non_interactive,
    )
    model_name_value = _required_value(
        model_name,
        prompt="LLM model name",
        default="gpt-4o-mini",
        non_interactive=non_interactive,
    )
    api_key_value = _required_value(
        api_key,
        prompt="LLM API key",
        default=None,
        hide_input=True,
        non_interactive=non_interactive,
    )

    wechat_enabled = _confirm_if_missing(
        wechat,
        prompt="Configure WeChat channel?",
        non_interactive=non_interactive,
    )
    feishu_enabled = _confirm_if_missing(
        feishu,
        prompt="Configure Feishu channel?",
        non_interactive=non_interactive,
    )

    wechat_values = _channel_values(
        enabled=wechat_enabled,
        channel_name="WeChat",
        webhook_url=wechat_webhook_url,
        app_id=wechat_app_id,
        app_secret=wechat_app_secret,
        non_interactive=non_interactive,
    )
    feishu_values = _channel_values(
        enabled=feishu_enabled,
        channel_name="Feishu",
        webhook_url=feishu_webhook_url,
        app_id=feishu_app_id,
        app_secret=feishu_app_secret,
        non_interactive=non_interactive,
    )

    config = _load_or_default_config(config_path)
    config = config.model_copy(
        update={
            "deployment": DeploymentConfig(
                llm=ModelProviderConfig(
                    provider=provider_value,
                    base_url=base_url_value,
                    model_name=model_name_value,
                    api_key_env="AUTORESEARCH_LLM_API_KEY",
                ),
                wechat=MessagingChannelConfig(
                    enabled=wechat_enabled,
                    webhook_url_env="AUTORESEARCH_WECHAT_WEBHOOK_URL"
                    if wechat_values["webhook_url"]
                    else None,
                    app_id_env="AUTORESEARCH_WECHAT_APP_ID" if wechat_values["app_id"] else None,
                    app_secret_env=(
                        "AUTORESEARCH_WECHAT_APP_SECRET"
                        if wechat_values["app_secret"]
                        else None
                    ),
                ),
                feishu=MessagingChannelConfig(
                    enabled=feishu_enabled,
                    webhook_url_env="AUTORESEARCH_FEISHU_WEBHOOK_URL"
                    if feishu_values["webhook_url"]
                    else None,
                    app_id_env="AUTORESEARCH_FEISHU_APP_ID" if feishu_values["app_id"] else None,
                    app_secret_env=(
                        "AUTORESEARCH_FEISHU_APP_SECRET"
                        if feishu_values["app_secret"]
                        else None
                    ),
                ),
            )
        }
    )

    parser = ConfigParser()
    config_path.parent.mkdir(parents=True, exist_ok=True)
    parser.write_file(config, config_path)

    env_values = {
        "AUTORESEARCH_LLM_PROVIDER": provider_value,
        "AUTORESEARCH_LLM_BASE_URL": base_url_value,
        "AUTORESEARCH_LLM_MODEL_NAME": model_name_value,
        "AUTORESEARCH_LLM_API_KEY": api_key_value,
        "AUTORESEARCH_WECHAT_WEBHOOK_URL": wechat_values["webhook_url"],
        "AUTORESEARCH_WECHAT_APP_ID": wechat_values["app_id"],
        "AUTORESEARCH_WECHAT_APP_SECRET": wechat_values["app_secret"],
        "AUTORESEARCH_FEISHU_WEBHOOK_URL": feishu_values["webhook_url"],
        "AUTORESEARCH_FEISHU_APP_ID": feishu_values["app_id"],
        "AUTORESEARCH_FEISHU_APP_SECRET": feishu_values["app_secret"],
    }
    env_example_path, env_example_created = _ensure_env_example(env_path)
    _merge_env_file(env_path, env_values)

    typer.echo(f"[OK] config written: {config_path}")
    typer.echo(f"[OK] env written: {env_path}")
    typer.echo(
        f"[OK] env template {'created' if env_example_created else 'ready'}: {env_example_path}"
    )
    typer.echo(f"[OK] model: {provider_value} / {model_name_value}")
    typer.echo(f"[OK] wechat: {'enabled' if wechat_enabled else 'disabled'}")
    typer.echo(f"[OK] feishu: {'enabled' if feishu_enabled else 'disabled'}")


@app.command("literature-refresh")
def literature_refresh(
    vault: Annotated[
        Path,
        typer.Option("--vault", help="Obsidian vault root to read and update."),
    ] = Path("autoresearch-vault"),
    cache: Annotated[
        Path,
        typer.Option("--cache", help="Retrieval cache directory."),
    ] = Path(".cache/literature"),
    max_queries: Annotated[
        int,
        typer.Option("--max-queries", min=1, help="Maximum optimized queries to run."),
    ] = 5,
    max_results_per_source: Annotated[
        int,
        typer.Option("--max-results-per-source", min=1, help="Maximum papers per source/query."),
    ] = 20,
    cache_ttl_hours: Annotated[
        int,
        typer.Option("--cache-ttl-hours", min=1, help="Cache TTL for source responses."),
    ] = 24,
    env_path: Annotated[
        Path,
        typer.Option("--env-path", help="Optional .env file for literature API keys."),
    ] = Path(".env"),
) -> None:
    """Run real online literature refresh and write an Obsidian summary."""

    try:
        _load_optional_env(env_path)
        report = run_daily_literature_refresh(
            vault_root=vault,
            cache_root=cache,
            config=LiteratureRefreshConfig(
                max_queries=max_queries,
                max_results_per_source=max_results_per_source,
                cache_ttl_hours=cache_ttl_hours,
            ),
        )
    except Exception as exc:
        typer.echo(f"[FAIL] literature refresh failed: {exc}", err=True)
        raise typer.Exit(code=1) from exc

    _echo_fetches(report.fetches)
    if not report.documents:
        typer.echo("[FAIL] literature refresh returned no source-backed documents", err=True)
        raise typer.Exit(code=1)

    typer.echo(f"[OK] queries: {len(report.queries)}")
    typer.echo(f"[OK] documents: {len(report.documents)}")
    if report.summary_path is not None:
        typer.echo(f"[OK] summary: {report.summary_path}")


@app.command("similarity-check")
def similarity_check(
    candidate_file: Annotated[
        Path,
        typer.Option(
            "--candidate-file",
            "-f",
            help="JSON file containing a ResearchCandidate payload.",
        ),
    ],
    vault: Annotated[
        Path,
        typer.Option("--vault", help="Obsidian vault root to read and update."),
    ] = Path("autoresearch-vault"),
    cache: Annotated[
        Path,
        typer.Option("--cache", help="Retrieval cache directory."),
    ] = Path(".cache/literature"),
    max_queries: Annotated[
        int,
        typer.Option("--max-queries", min=1, help="Maximum optimized queries to run."),
    ] = 6,
    max_results_per_source: Annotated[
        int,
        typer.Option("--max-results-per-source", min=1, help="Maximum papers per source/query."),
    ] = 10,
    cache_ttl_hours: Annotated[
        int,
        typer.Option("--cache-ttl-hours", min=1, help="Cache TTL for source responses."),
    ] = 24,
    project_id: Annotated[
        str | None,
        typer.Option("--project-id", help="Optional project ID to link the report into project knowledge."),
    ] = None,
    env_path: Annotated[
        Path,
        typer.Option("--env-path", help="Optional .env file for literature API keys."),
    ] = Path(".env"),
) -> None:
    """Run real online project-start similar-work checking for one candidate."""

    try:
        _load_optional_env(env_path)
        candidate = _load_candidate(candidate_file)
        report = run_project_similarity_check(
            candidate=candidate,
            vault_root=vault,
            cache_root=cache,
            config=SimilarityCheckConfig(
                max_queries=max_queries,
                max_results_per_source=max_results_per_source,
                cache_ttl_hours=cache_ttl_hours,
            ),
        )
        project_link = (
            link_similarity_report_to_project(
                report=report,
                vault_root=vault,
                project_id=project_id,
            )
            if project_id
            else None
        )
    except Exception as exc:
        typer.echo(f"[FAIL] similarity check failed: {exc}", err=True)
        raise typer.Exit(code=1) from exc

    _echo_fetches(report.fetches)
    if not report.findings:
        typer.echo("[FAIL] similarity check returned no source-backed findings", err=True)
        raise typer.Exit(code=1)

    typer.echo(f"[OK] candidate: {candidate.id}")
    typer.echo(f"[OK] queries: {len(report.queries)}")
    typer.echo(f"[OK] findings: {len(report.findings)}")
    if report.summary_path is not None:
        typer.echo(f"[OK] summary: {report.summary_path}")
    if project_link is not None:
        typer.echo(f"[OK] project_link: {project_link}")


@app.command("run-demo")
def run_demo(
    demo: str = typer.Option(
        "tabular_baseline",
        "--demo",
        "-d",
        help="ScientistBench-Lite demo task to run.",
    ),
    output_dir: Path = typer.Option(
        Path("runs/demo"),
        "--output-dir",
        "-o",
        help="Directory where demo outputs should be persisted.",
    ),
    timeout_seconds: int = typer.Option(
        30,
        "--timeout-seconds",
        help="Local execution timeout for the generated demo runner.",
    ),
) -> None:
    """Run one local MVP demo from generated code to evidence-backed report."""

    try:
        result = run_scientistbench_demo(
            demo,
            output_dir=output_dir,
            timeout_seconds=timeout_seconds,
        )
    except ValueError as exc:
        raise typer.BadParameter(str(exc)) from exc
    except Exception as exc:
        typer.echo(f"[FAIL] demo run failed: {exc}", err=True)
        raise typer.Exit(code=1) from exc

    typer.echo(f"[OK] demo: {result.demo}")
    typer.echo(f"[OK] experiment_dir: {result.experiment_dir}")
    typer.echo(f"[OK] run_id: {result.run_id}")
    typer.echo(f"[OK] validation: {result.validation_json_path}")
    typer.echo(f"[OK] evidence_map: {result.evidence_map_path}")
    typer.echo(f"[OK] report: {result.report_path}")


@app.command("validate-package")
def validate_package(
    manifest: Path = typer.Option(
        Path("manifest.json"),
        "--manifest",
        "-m",
        help="Path to a reproducibility package manifest.json file.",
    ),
) -> None:
    """Validate a reproducibility package manifest and included artifacts."""

    report = validate_reproducibility_package(manifest)
    if report.status is ValidationStatus.PASSED:
        typer.echo(f"[OK] package validation passed: {report.checked_artifacts} artifacts")
        return

    typer.echo(f"[FAIL] package validation failed: {report.checked_artifacts} artifacts")
    for issue in report.issues:
        target = f" ({issue.package_path})" if issue.package_path else ""
        typer.echo(f"[{issue.severity.value.upper()}] {issue.check}{target}: {issue.message}")
    raise typer.Exit(code=1)


@app.command("llm-smoke")
def llm_smoke(
    config_path: Annotated[
        Path,
        typer.Option("--config", "-c", help="Configuration file written by deploy-setup."),
    ] = Path("config.yaml"),
    env_path: Annotated[
        Path,
        typer.Option("--env-path", help="Local .env file containing the configured API key."),
    ] = Path(".env"),
    output: Annotated[
        Path,
        typer.Option("--output", help="JSON quality report output path under ignored run artifacts."),
    ] = Path("runs/llm-smoke/latest.json"),
    min_quality_score: Annotated[
        float,
        typer.Option("--min-quality-score", min=0.0, max=1.0, help="Fail below this score."),
    ] = 0.85,
    max_tokens: Annotated[
        int,
        typer.Option("--max-tokens", min=128, help="Maximum output tokens for the smoke request."),
    ] = 600,
) -> None:
    """Call the configured live LLM API and run a structured output quality gate."""

    try:
        result = run_llm_smoke_test(
            config_path=config_path,
            env_path=env_path,
            max_tokens=max_tokens,
        )
    except LLMClientError as exc:
        typer.echo(f"[FAIL] LLM smoke request failed: {exc}", err=True)
        raise typer.Exit(1) from exc

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(result.model_dump_json(indent=2), encoding="utf-8")
    typer.echo(f"[OK] provider: {result.provider}")
    typer.echo(f"[OK] model: {result.model_name}")
    typer.echo(f"[OK] endpoint: {result.endpoint}")
    typer.echo(f"[OK] quality_score: {result.quality.score:.3f}")
    for check, passed in result.quality.checks.items():
        typer.echo(f"[CHECK] {check}: {'pass' if passed else 'fail'}")

    parsed = result.quality.parsed_output or {}
    summary = parsed.get("summary")
    evidence_policy = parsed.get("evidence_policy")
    if isinstance(summary, str):
        typer.echo(f"[SUMMARY] {summary}")
    if isinstance(evidence_policy, str):
        typer.echo(f"[EVIDENCE] {evidence_policy}")
    typer.echo(f"[OK] report written: {output}")
    if result.quality.score < min_quality_score:
        typer.echo("[FAIL] LLM output quality score below threshold", err=True)
        raise typer.Exit(1)


@slash_app.command("init")
def init_slash_commands(
    directory: Annotated[
        Path,
        typer.Option(
            "--directory",
            "-d",
            help="Project slash command directory to create.",
        ),
    ] = Path(".autoresearch/commands"),
    force: Annotated[
        bool,
        typer.Option("--force", help="Overwrite existing command definitions."),
    ] = False,
) -> None:
    """Create project-scoped slash command templates."""

    written = 0
    skipped = 0
    for relative_path, (description, prompt) in DEFAULT_SLASH_COMMANDS.items():
        target = directory / relative_path
        if target.exists() and not force:
            skipped += 1
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_slash_command_toml(description, prompt), encoding="utf-8")
        written += 1

    typer.echo(f"[OK] slash commands written: {written}")
    typer.echo(f"[OK] slash commands skipped: {skipped}")
    typer.echo(f"[OK] directory: {directory}")


@slash_app.command("list")
def list_slash_commands(
    directory: Annotated[
        Path,
        typer.Option(
            "--directory",
            "-d",
            help="Project slash command directory to inspect.",
        ),
    ] = Path(".autoresearch/commands"),
) -> None:
    """List project-scoped slash command templates."""

    if not directory.exists():
        typer.echo(f"[FAIL] slash command directory does not exist: {directory}", err=True)
        raise typer.Exit(code=1)
    commands = sorted(directory.rglob("*.toml"))
    for command in commands:
        name = command.relative_to(directory).with_suffix("").as_posix().replace("/", ":")
        typer.echo(f"/{name}")


def _can_import(module_name: str) -> bool:
    try:
        import_module(module_name)
    except Exception:
        return False
    return True


def _load_or_default_config(config_path: Path) -> SystemConfig:
    if not config_path.exists():
        return SystemConfig()
    parser = ConfigParser()
    config = parser.parse_file(config_path)
    if not isinstance(config, SystemConfig):
        msg = f"{config_path} did not parse as SystemConfig"
        raise typer.BadParameter(msg)
    return config


def _load_candidate(candidate_file: Path) -> ResearchCandidate:
    try:
        text = candidate_file.read_text(encoding="utf-8-sig")
    except OSError as exc:
        msg = f"Could not read candidate file {candidate_file}: {exc}"
        raise typer.BadParameter(msg) from exc
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        msg = f"Invalid candidate JSON at line {exc.lineno}, column {exc.colno}: {exc.msg}"
        raise typer.BadParameter(msg) from exc
    try:
        return ResearchCandidate.model_validate(data)
    except Exception as exc:
        msg = f"Invalid ResearchCandidate payload: {exc}"
        raise typer.BadParameter(msg) from exc


def _echo_fetches(fetches: Iterable[object]) -> None:
    for fetch in fetches:
        source = getattr(fetch, "source", "unknown")
        query = getattr(fetch, "query", "unknown")
        paper_count = getattr(fetch, "paper_count", 0)
        cache_hit = getattr(fetch, "cache_hit", False)
        error = getattr(fetch, "error", None)
        cache_status = "hit" if cache_hit else "miss"
        error_text = f", error={error}" if error else ""
        typer.echo(
            f"[FETCH] source={source} papers={paper_count} cache={cache_status} "
            f"query={query}{error_text}"
        )


def _required_value(
    value: str | None,
    *,
    prompt: str,
    default: str | None,
    non_interactive: bool,
    hide_input: bool = False,
) -> str:
    if value:
        return value
    if non_interactive:
        msg = f"{prompt} is required in --non-interactive mode"
        raise typer.BadParameter(msg)
    prompted = typer.prompt(prompt, default=default, hide_input=hide_input)
    if not isinstance(prompted, str) or not prompted.strip():
        msg = f"{prompt} is required"
        raise typer.BadParameter(msg)
    return prompted.strip()


def _confirm_if_missing(
    value: bool | None,
    *,
    prompt: str,
    non_interactive: bool,
) -> bool:
    if value is not None:
        return value
    if non_interactive:
        return False
    return typer.confirm(prompt, default=False)


def _channel_values(
    *,
    enabled: bool,
    channel_name: str,
    webhook_url: str | None,
    app_id: str | None,
    app_secret: str | None,
    non_interactive: bool,
) -> dict[str, str | None]:
    if not enabled:
        return {"webhook_url": None, "app_id": None, "app_secret": None}
    values = {
        "webhook_url": webhook_url,
        "app_id": app_id,
        "app_secret": app_secret,
    }
    if non_interactive:
        if not values["webhook_url"] and not (values["app_id"] and values["app_secret"]):
            msg = (
                f"{channel_name} requires --{channel_name.lower()}-webhook-url or both "
                f"--{channel_name.lower()}-app-id and --{channel_name.lower()}-app-secret"
            )
            raise typer.BadParameter(msg)
        return values

    if values["webhook_url"] is None:
        values["webhook_url"] = typer.prompt(
            f"{channel_name} webhook URL (optional)",
            default="",
        ).strip() or None
    if values["app_id"] is None:
        values["app_id"] = typer.prompt(f"{channel_name} app ID (optional)", default="").strip() or None
    if values["app_secret"] is None:
        values["app_secret"] = (
            typer.prompt(f"{channel_name} app secret (optional)", default="", hide_input=True).strip()
            or None
        )
    if not values["webhook_url"] and not (values["app_id"] and values["app_secret"]):
        msg = f"{channel_name} channel needs a webhook URL or app ID plus app secret"
        raise typer.BadParameter(msg)
    return values


def _merge_env_file(env_path: Path, values: dict[str, str | None]) -> None:
    existing = _read_env_file(env_path)
    for key, value in values.items():
        if value is not None:
            existing[key] = value
    env_path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by autoresearch deploy-setup"]
    lines.extend(f"{key}={value}" for key, value in sorted(existing.items()))
    env_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _ensure_env_example(env_path: Path) -> tuple[Path, bool]:
    env_example_path = env_path.with_name(".env.example")
    if env_example_path.exists():
        return env_example_path, False
    env_example_path.parent.mkdir(parents=True, exist_ok=True)
    env_example_path.write_text(ENV_EXAMPLE_TEXT, encoding="utf-8")
    return env_example_path, True


def _load_optional_env(env_path: Path) -> None:
    if env_path.exists():
        load_dotenv(env_path, override=True)


def _read_env_file(env_path: Path) -> dict[str, str]:
    if not env_path.exists():
        return {}
    values: dict[str, str] = {}
    for line in env_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def _slash_command_toml(description: str, prompt: str) -> str:
    escaped_description = description.replace("\\", "\\\\").replace('"', '\\"')
    escaped_prompt = prompt.replace('"""', '\\"\\"\\"')
    return f'description="{escaped_description}"\nprompt = """\n{escaped_prompt}\n"""\n'


def _parser_available() -> bool:
    try:
        parser = ConfigParser()
        text = parser.format(SystemConfig(), ConfigFormat.JSON)
        parser.parse_text(text, config_format=ConfigFormat.JSON)
    except Exception:
        return False
    return True


if __name__ == "__main__":
    app()
