"""Competition-first unattended research contracts and runtime."""

from .manifest import (
    ManifestIntegrityError,
    build_competition_submission,
    canonical_model_hash,
    load_cycle_manifest,
    validate_cycle_evidence,
    write_cycle_manifest,
)
from .mdbench import MDBenchAdapter
from .models import (
    AccessKind,
    AccessRequest,
    AttemptStatus,
    CapabilityGrant,
    ClaimBinding,
    CompetitionRunSpec,
    CompetitionScorecard,
    CompetitionSubmission,
    CycleManifest,
    CycleOutcome,
    CycleResult,
    CycleStage,
    EvidenceGateReport,
    ExperimentAttempt,
    ExperimentProtocol,
    HypothesisProposal,
    MDBenchArchiveManifest,
    MDBenchDatasetArtifact,
    MDBenchDatasetFile,
    MDBenchExperimentMatrix,
    MDBenchMatrixAttemptSpec,
    MDBenchMethodSpec,
    MDBenchOfficialPreflight,
    MDBenchSystemCase,
    MDBenchTemporalSplit,
    ResearchOperation,
    ResearchTaskSpec,
    TopicCandidate,
    TopicFeasibility,
    TopicMode,
    TopicSelectionReport,
)
from .official import run_mdbench_official_preflight
from .official_data import (
    MDBenchDataError,
    download_mdbench_processed_archive,
    prepare_mdbench_official_data,
)
from .planning import PlanCompilationError, PlanCompiler, hypothesis_from_topic
from .preregistration import (
    MDBenchPreregistrationError,
    preregister_mdbench_gate_a,
    validate_mdbench_preregistration,
)
from .selection import TopicSelectionEngine, competition_topic_candidates
from .service import ResearchCycleService, load_capability_grant

__all__ = [
    "AccessKind",
    "AccessRequest",
    "AttemptStatus",
    "CapabilityGrant",
    "ClaimBinding",
    "CompetitionRunSpec",
    "CompetitionScorecard",
    "CompetitionSubmission",
    "CycleManifest",
    "CycleOutcome",
    "CycleResult",
    "CycleStage",
    "EvidenceGateReport",
    "ExperimentAttempt",
    "ExperimentProtocol",
    "HypothesisProposal",
    "MDBenchAdapter",
    "MDBenchArchiveManifest",
    "MDBenchDataError",
    "MDBenchDatasetArtifact",
    "MDBenchDatasetFile",
    "MDBenchExperimentMatrix",
    "MDBenchMatrixAttemptSpec",
    "MDBenchMethodSpec",
    "MDBenchOfficialPreflight",
    "MDBenchPreregistrationError",
    "MDBenchSystemCase",
    "MDBenchTemporalSplit",
    "ManifestIntegrityError",
    "PlanCompilationError",
    "PlanCompiler",
    "ResearchCycleService",
    "ResearchOperation",
    "ResearchTaskSpec",
    "TopicCandidate",
    "TopicFeasibility",
    "TopicMode",
    "TopicSelectionEngine",
    "TopicSelectionReport",
    "build_competition_submission",
    "canonical_model_hash",
    "competition_topic_candidates",
    "download_mdbench_processed_archive",
    "hypothesis_from_topic",
    "load_capability_grant",
    "load_cycle_manifest",
    "prepare_mdbench_official_data",
    "preregister_mdbench_gate_a",
    "run_mdbench_official_preflight",
    "validate_cycle_evidence",
    "validate_mdbench_preregistration",
    "write_cycle_manifest",
]
