"""Competition-first unattended research contracts and runtime."""

from .manifest import (
    ManifestIntegrityError,
    build_competition_submission,
    canonical_model_hash,
    load_cycle_manifest,
    validate_cycle_evidence,
    write_cycle_manifest,
)
from .mdbench import MDBenchAdapter
from .models import (
    AccessKind,
    AccessRequest,
    AttemptStatus,
    CapabilityGrant,
    ClaimBinding,
    CompetitionRunSpec,
    CompetitionScorecard,
    CompetitionSubmission,
    CycleManifest,
    CycleOutcome,
    CycleResult,
    CycleStage,
    EvidenceGateReport,
    ExperimentAttempt,
    ExperimentProtocol,
    HypothesisProposal,
    MDBenchDatasetFile,
    MDBenchOfficialPreflight,
    ResearchOperation,
    ResearchTaskSpec,
    TopicCandidate,
    TopicFeasibility,
    TopicMode,
    TopicSelectionReport,
)
from .official import run_mdbench_official_preflight
from .planning import PlanCompilationError, PlanCompiler, hypothesis_from_topic
from .selection import TopicSelectionEngine, competition_topic_candidates
from .service import ResearchCycleService, load_capability_grant

__all__ = [
    "AccessKind",
    "AccessRequest",
    "AttemptStatus",
    "CapabilityGrant",
    "ClaimBinding",
    "CompetitionRunSpec",
    "CompetitionScorecard",
    "CompetitionSubmission",
    "CycleManifest",
    "CycleOutcome",
    "CycleResult",
    "CycleStage",
    "EvidenceGateReport",
    "ExperimentAttempt",
    "ExperimentProtocol",
    "HypothesisProposal",
    "MDBenchAdapter",
    "MDBenchDatasetFile",
    "MDBenchOfficialPreflight",
    "ManifestIntegrityError",
    "PlanCompilationError",
    "PlanCompiler",
    "ResearchCycleService",
    "ResearchOperation",
    "ResearchTaskSpec",
    "TopicCandidate",
    "TopicFeasibility",
    "TopicMode",
    "TopicSelectionEngine",
    "TopicSelectionReport",
    "build_competition_submission",
    "canonical_model_hash",
    "competition_topic_candidates",
    "hypothesis_from_topic",
    "load_capability_grant",
    "load_cycle_manifest",
    "run_mdbench_official_preflight",
    "validate_cycle_evidence",
    "write_cycle_manifest",
]
